channels:
  - conda-forge
  - r
dependencies:
  - matplotlib
  - seaborn
  - numpy
  - pandas
  - rpy2
  - rise
  - jupyter_contrib_nbextensions
  - genepattern jupyter-wysiwyg
  - r-irkernel
  - r-tidyverse
  - pip
  - pip:
      - julia
      
  
